// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Untitled', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Untitled', async function() {
    // Test name: Untitled
    // Step # | name | target | value
    // 1 | open | /en | 
    await driver.get("https://www.sekaiglory.com/en")
    // 2 | setWindowSize | 899x876 | 
    await driver.manage().window().setRect({ width: 899, height: 876 })
    // 3 | click | css=g > path | 
    await driver.findElement(By.css("g > path")).click()
    // 4 | click | css=.flex > .w-full > .bg-\[\#222222\] > .absolute:nth-child(1) | 
    await driver.findElement(By.css(".flex > .w-full > .bg-\\[\\#222222\\] > .absolute:nth-child(1)")).click()
    // 5 | click | css=.flex:nth-child(1) > .flex > .relative > .flex > div | 
    await driver.findElement(By.css(".flex:nth-child(1) > .flex > .relative > .flex > div")).click()
    // 6 | click | css=.border > .w-full | 
    await driver.findElement(By.css(".border > .w-full")).click()
    // 7 | click | css=.p-3 | 
    await driver.findElement(By.css(".p-3")).click()
    // 8 | click | css=.relative:nth-child(4) > .rounded-full > .relative | 
    await driver.findElement(By.css(".relative:nth-child(4) > .rounded-full > .relative")).click()
    // 9 | click | css=.relative:nth-child(2) > .rounded-full > .relative | 
    await driver.findElement(By.css(".relative:nth-child(2) > .rounded-full > .relative")).click()
    // 10 | click | css=.relative:nth-child(3) > .rounded-full > .relative | 
    await driver.findElement(By.css(".relative:nth-child(3) > .rounded-full > .relative")).click()
    // 11 | mouseOver | css=.relative:nth-child(3) > .rounded-full > .relative | 
    {
      const element = await driver.findElement(By.css(".relative:nth-child(3) > .rounded-full > .relative"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 12 | mouseOut | css=.saturate-100 > .relative | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 13 | mouseOver | css=.w-\[80px\] | 
    {
      const element = await driver.findElement(By.css(".w-\\[80px\\]"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 14 | click | css=.w-\[80px\] | 
    await driver.findElement(By.css(".w-\\[80px\\]")).click()
    // 15 | mouseOut | css=.w-\[80px\] | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 16 | click | css=.inline-flex | 
    await driver.findElement(By.css(".inline-flex")).click()
    // 17 | mouseOver | css=.relative:nth-child(3) > .rounded-full > .relative | 
    {
      const element = await driver.findElement(By.css(".relative:nth-child(3) > .rounded-full > .relative"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 18 | mouseOut | css=.relative:nth-child(3) > .rounded-full > .relative | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 19 | close |  | 
    await driver.close()
  })
})
